---
- hosts: local

  vars:
  - vimdir: ~/.vim
  - vimrc: ~/.vimrc
  - gvimrc: ~/.gvimrc
  - bundledir: "{{vimdir}}/bundle"
  - vimspell: http://ftp.vim.org/vim/runtime/spell

  tasks:
    - name: create bundles directory
      file: path={{bundledir}} state=directory

    - name: create cache directory
      file: path=~/.cache/vim state=directory

    - name: link vimrc
      file: src={{vimdir}}/vimrc dest={{vimrc}} state=link force=yes

    - name: link gvimrc
      file: src={{vimdir}}/gvimrc dest={{gvimrc}} state=link force=yes

    - name: install package manager
      action: vim_plugin name=neobundle

    - name: install plugins
      action: vim_plugin name=all
      register: neobundle_install

    - name: create spell files directory
      file: path={{vimdir}}/spell state=directory

    - name: install spell files
      get_url:
        url: "{{vimspell}}/{{item[0]}}.{{item[1]}}.{{item[2]}}"
        dest: "{{vimdir}}/spell/{{item[0]}}.{{item[1]}}.{{item[2]}}"
      with_nested:
      - [en, es]
      - [latin1, utf-8]
      - [spl, sug]
